image: node:10-alpine

stages:
  - test

lint:
  stage: test
  script:
    - npm ci
    - npm run test

coverage:
  stage: test
  script:
    - npm run coverage
  coverage: '/All test \(\d+.\d+\%\)/'
